#!/usr/bin/env bash

# need to ask for sudo
if [[ $UID != 0 && "$1" != "install" && "$1" != "use" ]]
then
    sudo spam "$@"
    exit 0
fi

SOURCE="$(readlink ${BASH_SOURCE[0]})"
DIR=$(cd $(php -r "echo dirname('$SOURCE');") && pwd)

[ $(which php7.3) ] && php7.3 $DIR/cli/spam.php "$@" || php $DIR/cli/spam.php "$@"